<h3 class="mensajeGenerico">
    Confirmar Desucripción_</h3> 
<div data-role="content"> 
    <form data-ajax="false" action=""  method="post" Enctype="multipart/form-data">
            <ul data-role="listview" data-inset="true">
                <input type="hidden" name="catalogo" value="<?php echo $this->catalogo; ?>">
                <input type="hidden" name="descargar" value="true">
                <li>
                    <button type="submit" style="color:white" >[&nbsp;&nbsp;Aceptar_</button>
                    <div id="moopio">
                        <a href='#' data-rel='back' style="color:white" data-role='button' >[&nbsp;&nbsp;Cancelar_</a>
                    </div>
                </li>
            </ul>
        </form>
</div>