<!--<div id="prueba_master" class="wlp-bighorn-book">
    <div class="wlp-bighorn-book-content">
        <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
            <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">
                <div style="position:relative;  ">
                    <img width="100%"   src="<?php echo STATIC_URL ?>img/realtones/pre-suscripcion.png">
                    <div ><a href="/pe/realtones/suscripcion">
                            <img  width="39%" style="position:absolute; bottom:3%;right: 4%"  src="<?php echo STATIC_URL ?>img/fulltracks/buttonClickAqui.png">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>-->
<div id="prueba_master" class="wlp-bighorn-book">
    <div class="wlp-bighorn-book-content">
        <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
            <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">
                <table class="artist-photo">
                    <tr>
                        <td class="artist"  colspan=2 >
                            <div class="artist-text">
                                <div class="title-title" style="color: black;font-size:18px">
                                  Suscribete a TONOS. Cada semana elige y decarga un
                                        TONO de la ista que te enviaremos.
                                        Costo semanal S/ 4.90. Para CANCELAR envia SALIR al 4556
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="artist"  colspan=2 >
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="color: black;font-size:18px"
                                       href="/pe/realtones/legal">Términos y Condiciones
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <br>
                <!----------------TONOS------------------------------------->
                <table class="artist-photo">
                    <tr>
                        <td class="artist"  colspan=2 style="background-color: orange">
                            <form action="<?php echo $this->action; ?>"  method="get" Enctype="multipart/form-data">
                                <input type="hidden" name="numero" value="<?php echo $this->numero; ?>">
                                <div class="artist-text">
                                    <div class="title-img">
                                        <button style="border:none;background-color: orange;color: white;font-size:18px" type="submit">SUSCRIBIRME
                                         </button>
                                    </div>
                                </div>
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <td class="artist"  colspan=2 style="background-color: orange">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="color: white;font-size:18px"
                                       href="http://m.entretenimiento.entel.pe">CANCELAR
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    
                </table>
            </div>
        </div>
    </div>
</div>
